# Check docker compose and daemon status
$DockerRunning = $false
try {
    if (Get-Command docker -ErrorAction SilentlyContinue) {
        $info = docker info 2>$null
        if ($LASTEXITCODE -eq 0) {
            $DockerRunning = $true
        }
    }
} catch {}

if ($DockerRunning) {
    Write-Host "========================================================="
    Write-Host "       CRCI Live Demo Path (Docker Container Mode)       "
    Write-Host "========================================================="
    Write-Host ""
    Write-Host "[1/4] Building and launching node-alpha, node-beta, and dashboard..."
    docker compose up -d --build node-alpha node-beta dashboard

    function Cleanup-Stack {
        Write-Host ""
        Write-Host "========================================================="
        Write-Host "       Tearing down CRCI Live Demo Stack                 "
        Write-Host "========================================================="
        docker compose down
    }

    try {
        # 2. Wait for API to be healthy
        Write-Host ""
        Write-Host "[2/4] Waiting for node-alpha API to be healthy on port 8080..."
        while ($true) {
            try {
                $resp = Invoke-RestMethod -Uri "http://localhost:8080/health" -Method Get -ErrorAction SilentlyContinue
                if ($resp.status -eq "ok") {
                    break
                }
            } catch {}
            Start-Sleep -Seconds 1
        }
        Write-Host "✓ node-alpha API is healthy!"

        # 3. Wait for Dashboard to be ready
        Write-Host "[3/4] Waiting for live dashboard to start on port 5173..."
        while ($true) {
            try {
                $web = Invoke-WebRequest -Uri "http://localhost:5173" -Method Head -ErrorAction SilentlyContinue
                if ($web.StatusCode -eq 200 -or $web.StatusCode -eq 304) {
                    break
                }
            } catch {}
            Start-Sleep -Seconds 1
        }
        Write-Host "✓ Live dashboard is ready!"

        # 4. Open dashboard in default browser
        $URL = "http://localhost:5173"
        Write-Host ""
        Write-Host "[4/4] Opening dashboard at $URL..."
        Start-Process $URL

        Write-Host ""
        Write-Host "========================================================="
        Write-Host "       Beginning Live Telemetry Injections               "
        Write-Host "========================================================="
        Write-Host "Note: Every message and eviction is generated by the real Rust mesh."
        Write-Host ""

        Start-Sleep -Seconds 4
        Write-Host "[Narration] Dispatching normal telemetry from node-beta to node-alpha..."
        docker compose exec node-beta crci-node --send "System status check: All systems normal." --to node-alpha:7001 --severity normal --node-id node-beta

        Start-Sleep -Seconds 5
        Write-Host "[Narration] Dispatching second normal telemetry report..."
        docker compose exec node-beta crci-node --send "Weather report: Clear skies, no network jitter." --to node-alpha:7001 --severity normal --node-id node-beta

        Start-Sleep -Seconds 5
        Write-Host "[Narration] Deploying adversarial Byzantine agent (node-byzantine)..."
        docker compose up -d node-byzantine

        Write-Host "[Narration] node-byzantine has joined the mesh and is flooding conflicting reports."
        Write-Host "[Narration] Watch the dashboard screen: its reputation will decay and trigger eviction..."

        Write-Host ""
        Write-Host "Demo is running. Press Ctrl+C to terminate the mesh and clean up."
        while ($true) {
            Start-Sleep -Seconds 1
        }
    }
    finally {
        Cleanup-Stack
    }
} else {
    Write-Host "========================================================="
    Write-Host "       CRCI Live Demo Path (Native Local Process Mode)    "
    Write-Host "========================================================="
    Write-Host "Warning: Docker daemon is not running. Using local processes fallback." -ForegroundColor Yellow
    Write-Host ""

    Write-Host "[1/4] Compiling Rust binaries and installing dashboard dependencies..." -ForegroundColor Gray
    cargo build
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Cargo build failed."
        exit 1
    }

    $ExePath = "target/debug/crci-node.exe"
    
    # Run npm install for dashboard
    Write-Host "Installing Vite dashboard dependencies..." -ForegroundColor Gray
    Push-Location docs/dashboard
    npm install
    Pop-Location

    # Process variables
    $AlphaProc = $null
    $BetaProc = $null
    $DashProc = $null
    $ByzProc = $null

    function Cleanup-Local {
        Write-Host ""
        Write-Host "========================================================="
        Write-Host "       Terminating Native Local Mesh Processes           "
        Write-Host "========================================================="
        if ($ByzProc) { Stop-Process -Id $ByzProc.Id -Force -ErrorAction SilentlyContinue }
        if ($BetaProc) { Stop-Process -Id $BetaProc.Id -Force -ErrorAction SilentlyContinue }
        if ($AlphaProc) { Stop-Process -Id $AlphaProc.Id -Force -ErrorAction SilentlyContinue }
        if ($DashProc) { Stop-Process -Id $DashProc.Id -Force -ErrorAction SilentlyContinue }
        # Cleanup potential orphans on these ports
        Get-Process | Where-Object { $_.Name -eq "crci-node" } | Stop-Process -Force -ErrorAction SilentlyContinue
    }

    try {
        Write-Host "[2/4] Starting node-alpha daemon..." -ForegroundColor Gray
        $AlphaProc = Start-Process $ExePath -ArgumentList "--listen", "127.0.0.1:7001", "--node-id", "node-alpha" -NoNewWindow -PassThru

        # Wait for API to be healthy
        Write-Host "Waiting for node-alpha API to be healthy on port 8080..."
        while ($true) {
            try {
                $resp = Invoke-RestMethod -Uri "http://localhost:8080/health" -Method Get -ErrorAction SilentlyContinue
                if ($resp.status -eq "ok") {
                    break
                }
            } catch {}
            Start-Sleep -Seconds 1
        }
        Write-Host "✓ node-alpha API is healthy!"

        Write-Host "Starting node-beta daemon..." -ForegroundColor Gray
        $BetaProc = Start-Process $ExePath -ArgumentList "--listen", "127.0.0.1:7002", "--node-id", "node-beta", "--peers", "127.0.0.1:7001" -NoNewWindow -PassThru

        # 3. Wait for Dashboard to be ready
        Write-Host "[3/4] Starting live dashboard Vite dev server on port 5173..."
        $DashProc = Start-Process npm -ArgumentList "run", "dev", "--", "--host", "0.0.0.0" -WorkingDirectory "docs/dashboard" -NoNewWindow -PassThru

        while ($true) {
            try {
                $web = Invoke-WebRequest -Uri "http://localhost:5173" -Method Head -ErrorAction SilentlyContinue
                if ($web.StatusCode -eq 200 -or $web.StatusCode -eq 304) {
                    break
                }
            } catch {}
            Start-Sleep -Seconds 1
        }
        Write-Host "✓ Live dashboard is ready!"

        # 4. Open dashboard in default browser
        $URL = "http://localhost:5173"
        Write-Host ""
        Write-Host "[4/4] Opening dashboard at $URL..."
        Start-Process $URL

        Write-Host ""
        Write-Host "========================================================="
        Write-Host "       Beginning Live Telemetry Injections               "
        Write-Host "========================================================="
        Write-Host "Note: Every message and eviction is generated by the real Rust mesh."
        Write-Host ""

        Start-Sleep -Seconds 4
        Write-Host "[Narration] Dispatching normal telemetry from node-beta to node-alpha..."
        Start-Process $ExePath -ArgumentList '--send "System status check: All systems normal." --to 127.0.0.1:7001 --severity normal --node-id node-beta' -NoNewWindow -Wait

        Start-Sleep -Seconds 5
        Write-Host "[Narration] Dispatching second normal telemetry report..."
        Start-Process $ExePath -ArgumentList '--send "Weather report: Clear skies, no network jitter." --to 127.0.0.1:7001 --severity normal --node-id node-beta' -NoNewWindow -Wait

        Start-Sleep -Seconds 5
        Write-Host "[Narration] Deploying adversarial Byzantine agent (node-byzantine)..."
        $ByzProc = Start-Process $ExePath -ArgumentList '--byzantine false_allclear --to 127.0.0.1:7001 --interval 500 --node-id node-byzantine' -NoNewWindow -PassThru

        Write-Host "[Narration] node-byzantine has joined the mesh and is flooding conflicting reports."
        Write-Host "[Narration] Watch the dashboard screen: its reputation will decay and trigger eviction..."

        Write-Host ""
        Write-Host "Demo is running. Press Ctrl+C to terminate the mesh and clean up."
        while ($true) {
            Start-Sleep -Seconds 1
        }
    }
    finally {
        Cleanup-Local
    }
}
