#!/usr/bin/env bash
set -euo pipefail

# Parse command-line flags
ALLOW_NATIVE=false
for arg in "$@"; do
  if [ "$arg" = "--native" ] || [ "$arg" = "--local" ]; then
    ALLOW_NATIVE=true
  fi
done

if [ "${DEMO_MODE:-}" = "native" ] || [ "${DEMO_MODE:-}" = "local" ]; then
  ALLOW_NATIVE=true
fi

# Check docker compose and daemon status
DOCKER_RUNNING=false
if command -v docker >/dev/null 2>&1; then
  if docker info >/dev/null 2>&1; then
    DOCKER_RUNNING=true
  fi
fi

if [ "$DOCKER_RUNNING" = false ] && [ "$ALLOW_NATIVE" = false ]; then
  echo "========================================================="
  echo "       CRCI Live Demo Path — Docker Unavailable          "
  echo "========================================================="
  echo ""
  echo "ERROR: Docker daemon is not running or accessible."
  echo "Diagnostic output from docker info:"
  docker info 2>&1 || true
  echo ""
  echo "Resolution options:"
  echo "  1. Start Docker Desktop and ensure the engine daemon is running."
  echo "     Then re-run: bash scripts/demo.sh"
  echo ""
  echo "  2. Alternatively, explicitly run native local process mode:"
  echo "     bash scripts/demo.sh --native"
  echo ""
  echo "Feature Gap Notice (Native Local Mode):"
  echo "  - Requires local Rust toolchain (cargo) and Node.js (npm) installed on host."
  echo "  - Binds directly to host localhost ports (7001, 7002, 8080, 5173)."
  echo "  - Metrics available via raw HTTP GET /metrics endpoint."
  echo "  - Does not provide container/network-level process isolation."
  echo "========================================================="
  exit 1
fi

if [ "$DOCKER_RUNNING" = true ] && [ "$ALLOW_NATIVE" = false ]; then
  echo "========================================================="
  echo "       CRCI Live Demo Path (Docker Container Mode)       "
  echo "========================================================="
  echo ""
  echo "[1/4] Building and launching node-alpha, node-beta, and dashboard..."
  docker compose up -d --build node-alpha node-beta dashboard

  cleanup() {
    echo ""
    echo "========================================================="
    echo "       Tearing down CRCI Live Demo Stack                 "
    echo "========================================================="
    docker compose down
  }
  trap cleanup EXIT

  # 2. Wait for API to be healthy
  echo ""
  echo "[2/4] Waiting for node-alpha API to be healthy on port 8080..."
  until curl -s http://localhost:8080/health | grep -q "status"; do
    sleep 1
  done
  echo "✓ node-alpha API is healthy!"

  # 3. Wait for Dashboard to be ready
  echo "[3/4] Waiting for live dashboard to start on port 5173..."
  until curl -s -I http://localhost:5173 | grep -q "200\|304\|404\|200 OK"; do
    sleep 1
  done
  echo "✓ Live dashboard is ready!"

  # 4. Open dashboard in default browser
  URL="http://localhost:5173"
  echo ""
  echo "[4/4] Opening dashboard at $URL..."
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$URL"
  elif command -v open >/dev/null 2>&1; then
    open "$URL"
  elif command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "$URL"
  else
    echo "Please open $URL manually in your web browser."
  fi

  echo ""
  echo "========================================================="
  echo "       Beginning Live Telemetry Injections               "
  echo "========================================================="
  echo "Note: Every message and eviction is generated by the real Rust mesh."
  echo ""

  sleep 4
  echo "[Narration] Dispatching normal telemetry from node-beta to node-alpha..."
  docker compose exec node-beta crci-node --send "System status check: All systems normal." --to node-alpha:7001 --severity normal --node-id node-beta

  sleep 5
  echo "[Narration] Dispatching second normal telemetry report..."
  docker compose exec node-beta crci-node --send "Weather report: Clear skies, no network jitter." --to node-alpha:7001 --severity normal --node-id node-beta

  sleep 5
  echo "[Narration] Deploying adversarial Byzantine agent (node-byzantine)..."
  docker compose up -d node-byzantine

  echo "[Narration] node-byzantine has joined the mesh and is flooding conflicting reports."
  echo "[Narration] Watch the dashboard screen: its reputation will decay and trigger eviction..."

  # Wait indefinitely for Ctrl+C
  echo ""
  echo "Demo is running. Press Ctrl+C to terminate the mesh and clean up."
  while true; do
    sleep 1
  done
else
  echo "========================================================="
  echo "       CRCI Live Demo Path (Native Local Process Mode)    "
  echo "========================================================="
  echo "Warning: Docker daemon is not running. Using local processes fallback."
  echo ""

  echo "[1/4] Compiling Rust binaries and installing dashboard dependencies..."
  cargo build
  
  EXE_PATH="target/debug/crci-node"
  if [ ! -f "$EXE_PATH" ] && [ -f "${EXE_PATH}.exe" ]; then
    EXE_PATH="${EXE_PATH}.exe"
  fi

  # Run npm install for dashboard
  echo "Installing Vite dashboard dependencies..."
  (cd web/dashboard && npm install)

  ALPHA_PID=""
  BETA_PID=""
  DASH_PID=""
  BYZ_PID=""

  cleanup_local() {
    echo ""
    echo "========================================================="
    echo "       Terminating Native Local Mesh Processes           "
    echo "========================================================="
    [ -n "$BYZ_PID" ] && kill $BYZ_PID 2>/dev/null || true
    [ -n "$BETA_PID" ] && kill $BETA_PID 2>/dev/null || true
    [ -n "$ALPHA_PID" ] && kill $ALPHA_PID 2>/dev/null || true
    [ -n "$DASH_PID" ] && kill $DASH_PID 2>/dev/null || true
    # Cleanup potential orphans
    killall crci-node 2>/dev/null || true
    killall crci-node.exe 2>/dev/null || true
  }
  trap cleanup_local EXIT

  echo "[2/4] Starting node-alpha daemon..."
  $EXE_PATH --listen 127.0.0.1:7001 --node-id node-alpha >/dev/null 2>&1 &
  ALPHA_PID=$!

  # Wait for API to be healthy
  echo "Waiting for node-alpha API to be healthy on port 8080..."
  until curl -s http://localhost:8080/health | grep -q "status"; do
    sleep 1
  done
  echo "✓ node-alpha API is healthy!"

  echo "Starting node-beta daemon..."
  $EXE_PATH --listen 127.0.0.1:7002 --node-id node-beta --peers 127.0.0.1:7001 >/dev/null 2>&1 &
  BETA_PID=$!

  # 3. Wait for Dashboard to be ready
  echo "[3/4] Starting live dashboard Vite dev server on port 5173..."
  (cd web/dashboard && npm run dev -- --host 0.0.0.0) >/dev/null 2>&1 &
  DASH_PID=$!

  while ! curl -s -I http://localhost:5173 | grep -q "200\|304\|404\|200 OK"; do
    sleep 1
  done
  echo "✓ Live dashboard is ready!"

  # 4. Open dashboard in default browser
  URL="http://localhost:5173"
  echo ""
  echo "[4/4] Opening dashboard at $URL..."
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$URL"
  elif command -v open >/dev/null 2>&1; then
    open "$URL"
  elif command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "$URL"
  else
    echo "Please open $URL manually in your web browser."
  fi

  echo ""
  echo "========================================================="
  echo "       Beginning Live Telemetry Injections               "
  echo "========================================================="
  echo "Note: Every message and eviction is generated by the real Rust mesh."
  echo ""

  sleep 4
  echo "[Narration] Dispatching normal telemetry from node-beta to node-alpha..."
  $EXE_PATH --send "System status check: All systems normal." --to 127.0.0.1:7001 --severity normal --node-id node-beta

  sleep 5
  echo "[Narration] Dispatching second normal telemetry report..."
  $EXE_PATH --send "Weather report: Clear skies, no network jitter." --to 127.0.0.1:7001 --severity normal --node-id node-beta

  sleep 5
  echo "[Narration] Deploying adversarial Byzantine agent (node-byzantine)..."
  $EXE_PATH --byzantine false_allclear --to 127.0.0.1:7001 --interval 500 --node-id node-byzantine >/dev/null 2>&1 &
  BYZ_PID=$!

  echo "[Narration] node-byzantine has joined the mesh and is flooding conflicting reports."
  echo "[Narration] Watch the dashboard screen: its reputation will decay and trigger eviction..."

  # Wait indefinitely for Ctrl+C
  echo ""
  echo "Demo is running. Press Ctrl+C to terminate the mesh and clean up."
  while true; do
    sleep 1
  done
fi
