package dev.crci.android

import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.viewModels
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import dev.crci.android.ui.NodeScreen

class MainActivity : ComponentActivity() {

    private val viewModel: CrciViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    NodeScreen(viewModel = viewModel)
                }
            }
        }
    }

    override fun onStart() {
        super.onStart()
        val intent = Intent(this, CrciService::class.java).apply {
            action = CrciService.ACTION_START
        }
        // Start foreground service handling is standard in modern Android apps
        startService(intent)
        viewModel.startNode()
    }

    override fun onStop() {
        super.onStop()
        // Wait, the prompt says "Stop CrciService with ACTION_STOP in onStop()".
        // But if we want the mesh to live in the background, we shouldn't stop it in onStop.
        // The prompt says "A foreground Service (CrciService) holds the runtime alive while the app is visible."
        // Oh, "while the app is visible." If the user wants it to stop on background, sure.
        val intent = Intent(this, CrciService::class.java).apply {
            action = CrciService.ACTION_STOP
        }
        startService(intent)
        viewModel.stopNode()
    }

    companion object {
        init {
            // Load the native library generated by UniFFI/Rust.
            // Ensure the .so files are placed in app/src/main/jniLibs.
            System.loadLibrary("crci_core")
        }
    }
}
