package dev.crci.android

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.viewModels
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import dev.crci.android.ui.NodeScreen

class MainActivity : ComponentActivity() {

    private val viewModel: CrciViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    NodeScreen(viewModel = viewModel)
                }
            }
        }
    }

    companion object {
        init {
            // Load the native library generated by UniFFI/Rust.
            // Ensure the .so files are placed in app/src/main/jniLibs.
            System.loadLibrary("crci_core")
        }
    }
}
